"""Reflection schemas for the Reflection section of the Daily Work Operating Loop.

This module defines the Pydantic models for Reflection entities, which represent
structured review items capturing progress, insights, and lessons learned.
Reflections use hybrid storage: content stored as files in filesystem,
metadata tracked in database.

Requirements: 28.2, 28.3
"""
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class ReflectionType(str, Enum):
    """Reflection type values.
    
    Requirement 28.3: THE System SHALL support reflection_type values:
    daily_recap, weekly_summary, lessons_learned.
    """
    DAILY_RECAP = "daily_recap"
    WEEKLY_SUMMARY = "weekly_summary"
    LESSONS_LEARNED = "lessons_learned"


class GeneratedBy(str, Enum):
    """Generated by values indicating who created the reflection.
    
    Requirement 28.4: THE System SHALL support generated_by values:
    user, agent, system.
    """
    USER = "user"
    AGENT = "agent"
    SYSTEM = "system"


class ReflectionCreate(BaseModel):
    """Request model for creating a new Reflection.
    
    Requirement 28.2: THE System SHALL store Reflection metadata in the database
    with fields: id, workspace_id, reflection_type, title, file_path,
    period_start, period_end, generated_by, created_at, updated_at.
    """
    workspace_id: str = Field(..., description="ID of the workspace this Reflection belongs to")
    reflection_type: ReflectionType = Field(
        ...,
        description="Type of reflection"
    )
    title: str = Field(..., min_length=1, max_length=500, description="Title of the Reflection")
    file_path: str = Field(..., min_length=1, max_length=1000, description="Relative path to the reflection file within the workspace")
    period_start: datetime = Field(..., description="Start of the period this reflection covers")
    period_end: datetime = Field(..., description="End of the period this reflection covers")
    generated_by: GeneratedBy = Field(
        default=GeneratedBy.USER,
        description="Who generated this reflection"
    )


class ReflectionUpdate(BaseModel):
    """Request model for updating an existing Reflection.
    
    All fields are optional - only provided fields will be updated.
    """
    reflection_type: Optional[ReflectionType] = Field(None, description="Type of reflection")
    title: Optional[str] = Field(None, min_length=1, max_length=500, description="Title of the Reflection")
    file_path: Optional[str] = Field(None, min_length=1, max_length=1000, description="Relative path to the reflection file")
    period_start: Optional[datetime] = Field(None, description="Start of the period this reflection covers")
    period_end: Optional[datetime] = Field(None, description="End of the period this reflection covers")
    generated_by: Optional[GeneratedBy] = Field(None, description="Who generated this reflection")


class ReflectionResponse(BaseModel):
    """Response model for Reflection entities.
    
    Requirement 28.2: THE System SHALL store Reflection metadata in the database
    with fields: id, workspace_id, reflection_type, title, file_path,
    period_start, period_end, generated_by, created_at, updated_at.
    """
    id: str = Field(..., description="Unique identifier for the Reflection")
    workspace_id: str = Field(..., description="ID of the workspace this Reflection belongs to")
    reflection_type: ReflectionType = Field(..., description="Type of reflection")
    title: str = Field(..., description="Title of the Reflection")
    file_path: str = Field(..., description="Relative path to the reflection file within the workspace")
    period_start: datetime = Field(..., description="Start of the period this reflection covers")
    period_end: datetime = Field(..., description="End of the period this reflection covers")
    generated_by: GeneratedBy = Field(..., description="Who generated this reflection")
    created_at: datetime = Field(..., description="Timestamp when the Reflection was created")
    updated_at: datetime = Field(..., description="Timestamp when the Reflection was last updated")
