"""Summary template — 2-card single-page layout (CEO/GM summary)."""

from utils import fmt_money, wow_str, wow_color, wow_arrow, now_cst
from html_helpers import fmt_week_dates, TD_STYLE


def generate_summary_html(data, weeks, title_override=None):
    """Generate a summary-style HTML report (2 cards + breakdown table)."""
    wf = fmt_week_dates(weeks)
    cw_start_fmt = wf["cw_start_fmt"]
    cw_end_fmt = wf["cw_end_fmt"]
    pw_start_fmt = wf["pw_start_fmt"]
    pw_end_fmt = wf["pw_end_fmt"]
    year = wf["year"]
    totals = data["totals"]
    rows = data["rows"]
    last_refresh = data["last_refresh"]

    # Data coverage warning
    cw_days = weeks.get("cw_days", 7)
    data_note = ""
    if cw_days < 7:
        data_note = (
            f'<div style="background:#fff3cd;border-left:4px solid #ffc107;padding:10px 14px;'
            f'margin-bottom:20px;font-size:13px;color:#856404;border-radius:0 4px 4px 0;">'
            f'⚠️ Current week window ({cw_start_fmt} – {cw_end_fmt}) has only {cw_days} of 7 days '
            f'with actual data. Values reflect actual data only — no backfill applied.</div>'
        )

    # Combined table rows
    combined_rows = ""
    for r in rows:
        rev_color = wow_color(r["rev_wow"])
        rev_arrow_v = wow_arrow(r["rev_wow"])
        usage_color = wow_color(r["usage_wow"])
        usage_arrow_v = wow_arrow(r["usage_wow"])
        combined_rows += (
            f'<tr style="background:white;">'
            f'<td style="{TD_STYLE}">{r["name"]}</td>'
            f'<td style="{TD_STYLE}text-align:right;">{fmt_money(r["cw_rev"])}</td>'
            f'<td style="{TD_STYLE}text-align:right;color:#888">{fmt_money(r["pw_rev"])}</td>'
            f'<td style="{TD_STYLE}text-align:right;color:{rev_color};font-weight:600">{rev_arrow_v} {wow_str(r["rev_wow"])}</td>'
            f'<td style="{TD_STYLE}text-align:right;border-left:2px solid #e8eaed;">{fmt_money(r["cw_usage"])}</td>'
            f'<td style="{TD_STYLE}text-align:right;color:#888">{fmt_money(r["pw_usage"])}</td>'
            f'<td style="{TD_STYLE}text-align:right;color:{usage_color};font-weight:600">{usage_arrow_v} {wow_str(r["usage_wow"])}</td>'
            f'</tr>'
        )

    # TOTAL row
    trc = wow_color(totals["rev_wow"]); tra = wow_arrow(totals["rev_wow"])
    tuc = wow_color(totals["usage_wow"]); tua = wow_arrow(totals["usage_wow"])
    combined_rows += (
        f'<tr style="background:#f0f4f8;border-top:2px solid #2b579a;">'
        f'<td style="{TD_STYLE}font-weight:700;">TOTAL</td>'
        f'<td style="{TD_STYLE}text-align:right;font-weight:700">{fmt_money(totals["cw_rev"])}</td>'
        f'<td style="{TD_STYLE}text-align:right;color:#888">{fmt_money(totals["pw_rev"])}</td>'
        f'<td style="{TD_STYLE}text-align:right;color:{trc};font-weight:600">{tra} {wow_str(totals["rev_wow"])}</td>'
        f'<td style="{TD_STYLE}text-align:right;font-weight:700;border-left:2px solid #e8eaed;">{fmt_money(totals["cw_usage"])}</td>'
        f'<td style="{TD_STYLE}text-align:right;color:#888">{fmt_money(totals["pw_usage"])}</td>'
        f'<td style="{TD_STYLE}text-align:right;color:{tuc};font-weight:600">{tua} {wow_str(totals["usage_wow"])}</td>'
        f'</tr>'
    )

    # Summary cards
    rev_c = wow_color(totals["rev_wow"]); rev_a = wow_arrow(totals["rev_wow"])
    usg_c = wow_color(totals["usage_wow"]); usg_a = wow_arrow(totals["usage_wow"])

    html = f'''<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f5f6fa;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
<table width="820" cellpadding="0" cellspacing="0" border="0" align="center" style="max-width:820px;background:white;">

    <!-- Header -->
    <tr>
        <td style="background:#1e3a5f;padding:28px 32px;">
            <h1 style="margin:0;font-size:22px;font-weight:600;letter-spacing:0.5px;color:white;">&#128202; {title_override or "CMHK Weekly CDER and Usage Report"}</h1>
            <p style="margin:6px 0 0;font-size:14px;color:#b0c4de;">{cw_start_fmt} &ndash; {cw_end_fmt}, {year} | Generated by DataRetriever &#128021;</p>
        </td>
    </tr>

    <tr><td style="padding:24px 32px;">

    {data_note}

    <!-- Summary Cards -->
    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:24px;">
        <tr>
            <td width="48%" style="background:#f8f9fc;padding:18px 20px;border-left:4px solid #2b579a;vertical-align:top;">
                <div style="font-size:12px;color:#666;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;">Total Revenue</div>
                <div style="font-size:26px;font-weight:700;color:#1a365d;">{fmt_money(totals["cw_rev"])}</div>
                <div style="font-size:14px;color:{rev_c};font-weight:600;margin-top:4px;">{rev_a} {wow_str(totals["rev_wow"])} WoW</div>
                <div style="font-size:12px;color:#999;margin-top:2px;">prev: {fmt_money(totals["pw_rev"])}</div>
            </td>
            <td width="4%">&nbsp;</td>
            <td width="48%" style="background:#f8f9fc;padding:18px 20px;border-left:4px solid #0a7c42;vertical-align:top;">
                <div style="font-size:12px;color:#666;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;">Total Usage</div>
                <div style="font-size:26px;font-weight:700;color:#1a365d;">{fmt_money(totals["cw_usage"])}</div>
                <div style="font-size:14px;color:{usg_c};font-weight:600;margin-top:4px;">{usg_a} {wow_str(totals["usage_wow"])} WoW</div>
                <div style="font-size:12px;color:#999;margin-top:2px;">prev: {fmt_money(totals["pw_usage"])}</div>
            </td>
        </tr>
    </table>

    <!-- Breakdown Table -->
    <h2 style="font-size:16px;color:#1a365d;margin:28px 0 12px;padding-bottom:8px;border-bottom:2px solid #e8eaed;">Revenue &amp; Usage Breakdown by Segment</h2>
    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;font-size:13px;">
        <thead>
            <tr style="background:#f0f4f8;">
                <th rowspan="2" style="padding:8px 10px;text-align:left;font-weight:600;color:#2b579a;border-bottom:2px solid #2b579a;vertical-align:bottom;">Segment</th>
                <th colspan="3" style="padding:8px 10px;text-align:center;font-weight:600;color:#2b579a;border-bottom:1px solid #c0c8d4;">Revenue</th>
                <th colspan="3" style="padding:8px 10px;text-align:center;font-weight:600;color:#0a7c42;border-bottom:1px solid #c0c8d4;border-left:2px solid #e8eaed;">Usage</th>
            </tr>
            <tr style="background:#f0f4f8;">
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #2b579a;font-size:11px;">CW<br/>{cw_start_fmt}&ndash;{cw_end_fmt}</th>
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #2b579a;font-size:11px;">PW<br/>{pw_start_fmt}&ndash;{pw_end_fmt}</th>
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #2b579a;font-size:11px;">WoW</th>
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #0a7c42;font-size:11px;border-left:2px solid #e8eaed;">CW<br/>{cw_start_fmt}&ndash;{cw_end_fmt}</th>
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #0a7c42;font-size:11px;">PW<br/>{pw_start_fmt}&ndash;{pw_end_fmt}</th>
                <th style="padding:6px 10px;text-align:right;font-weight:500;color:#666;border-bottom:2px solid #0a7c42;font-size:11px;">WoW</th>
            </tr>
        </thead>
        <tbody>
            {combined_rows}
        </tbody>
    </table>

    </td></tr>

    <!-- Footer -->
    <tr>
        <td style="background:#f5f6fa;padding:16px 32px;font-size:12px;color:#888;border-top:1px solid #e8eaed;">
            <p style="margin:0;">Data source: fact_estimated_revenue (Athena, cn-north-1) &bull; FBR only (fbr_flag=Y) &bull; Revenue = all charge types &bull; Usage = biz_charge_type_group 'Net Usage'</p>
            <p style="margin:4px 0 0;">Data refreshed: {last_refresh} &bull; Report generated: {now_cst()}</p>
        </td>
    </tr>
</table>
</body>
</html>'''

    return html
